### ISSUE TITLE
./cover.sh not working on server side

### ISSUE THREAD

**Issue by hitrzajc** [radumirea/ncmpcpp-with-cover-art#3]
i am guessing you can use cover.sh only on local computer.
```bash
./cover.sh
Traceback (most recent call last):
  File "/usr/sbin/ueberzug", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/ueberzug/__main__.py", line 55, in main
    module.main(options)
  File "/usr/lib/python3.10/site-packages/ueberzug/layer.py", line 206, in main
    window_infos = xutil.get_parent_window_infos()
  File "/usr/lib/python3.10/site-packages/ueberzug/xutil.py", line 171, in get_parent_window_infos
    pid_window_id_map = get_pid_window_id_map()
  File "/usr/lib/python3.10/site-packages/ueberzug/xutil.py", line 99, in get_pid_window_id_map
    .value)
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by radumirea** [comment]
Are you executing this on a server running mpd? All these files should be on the client machine running ncmpcpp.

The error message comes from ueberzug, probably because it needs to be run in a terminal window that's a Xorg client.

**Comment by hitrzajc** [comment]
yes I thought so. I was running it on TTY.
